[project]
name = "agentic-tools"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.12.12"
dependencies = [
    "faster-whisper>=1.2.1",
]

[project.scripts]
recording-transcribe = "main:recording_transcribe_main"
recording-categorize = "main:recording_categorize_main"
